# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wc8pkjL8niTGtpnWnlmWDhpCXuVvNIUg
"""

from fastapi import FastAPI, File, UploadFile, HTTPException
from fastapi.responses import JSONResponse
import torch
import torch.nn as nn
from torchvision import transforms, models
from PIL import Image
from huggingface_hub import hf_hub_download
import io


app = FastAPI(
    title="Plant Disease Classification API",
    description="Upload a plant leaf image to detect the disease.",
    version="1.0.0"
)


HF_REPO_ID = "arpigmm/plant-disease-model"
THRESHOLD  = 0.4
DEVICE     = torch.device("cuda" if torch.cuda.is_available() else "cpu")


transform = transforms.Compose([
    transforms.Resize((256, 256)),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])


def load_model():
    print(f" Downloading model from HuggingFace: {HF_REPO_ID}")

    model_path = hf_hub_download(
        repo_id=HF_REPO_ID,
        filename="best_model.pth"
    )

    checkpoint    = torch.load(model_path, map_location=DEVICE)
    label_map     = checkpoint['label_map']
    num_classes   = checkpoint['num_classes']
    label_to_name = {v: k for k, v in label_map.items()}

    model = models.resnet50(weights=None)
    in_features = model.fc.in_features
    model.fc = nn.Sequential(
        nn.Dropout(p=0.4),
        nn.Linear(in_features, 512),
        nn.ReLU(),
        nn.Dropout(p=0.3),
        nn.Linear(512, num_classes)
    )

    model.load_state_dict(checkpoint['model_state_dict'])
    model.to(DEVICE)
    model.eval()

    print(f" Model loaded — {num_classes} classes on {DEVICE}")
    return model, label_to_name


model, label_to_name = load_model()


@app.get("/")
def root():
    """Health check endpoint."""
    return {
        "status":  "ok",
        "message": "Plant Disease Classification API is running"
    }


@app.get("/classes")
def get_classes():
    """Returns all 40 disease classes the model can detect."""
    return {
        "num_classes": len(label_to_name),
        "classes":     sorted(label_to_name.values())
    }


@app.post("/predict")
async def predict(file: UploadFile = File(...)):
    """
    Upload a plant leaf image to detect the disease.

    - **file**: JPG or PNG image of a plant leaf

    Returns:
    - **disease**: detected disease name
    - **confidence**: model confidence score (0.0 to 1.0)
    - **reliable**: False if confidence is below threshold
    """

    if file.content_type not in ["image/jpeg", "image/png", "image/jpg"]:
        raise HTTPException(
            status_code=400,
            detail="Only JPG and PNG images are supported"
        )

    try:
        contents = await file.read()
        img      = Image.open(io.BytesIO(contents)).convert("RGB")
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Cannot read image: {e}")


    try:
        img_tensor = transform(img).unsqueeze(0).to(DEVICE)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Transform failed: {e}")

    try:
        with torch.no_grad():
            outputs               = model(img_tensor)
            probs                 = torch.softmax(outputs, dim=1)
            confidence, predicted = probs.max(dim=1)
            confidence            = round(confidence.item(), 4)
            predicted             = predicted.item()
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Prediction failed: {e}")

    if confidence < THRESHOLD:
        return JSONResponse(content={
            "disease":    "Uncertain — please try a clearer photo",
            "confidence": confidence,
            "reliable":   False,
            "tip":        "Make sure the diseased area is clearly visible and well-lit"
        })

    return JSONResponse(content={
        "disease":    label_to_name[predicted],
        "confidence": confidence,
        "reliable":   True
    })